version: '3.8'

services:
    app:
        image: php:8.3-fpm-alpine
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
        command: sh -c "docker-php-ext-install pdo pdo_mysql && php-fpm"

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: laravel_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        ports:
            - "3306:3306"
        networks:
            - laravel

    redis:
        image: redis:latest
        container_name: laravel_redis
        ports:
            - "6379:6379"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
